import React from "react";
import { TapeWidget } from "../components/AnimationComponents";

const HeroSection = () => {
  return (
    <div className="h-screen w-full flex flex-col justify-center items-center gap-6 overflow-hidden">
      <h1 className="text-9xl font-bold">
        Mayank Joshi{" "}
        <span className="h-4 w-4 bg-indigo-600 inline-block rounded-full animate-bounce"></span>
      </h1>
      <TapeWidget
        rotate={"rotate-6 origin-center translate-y-full"}
        content={[
          "React 🚀",
          "Redux",
          "Next",
          "Javascript",
          "Node",
          "Express",
          "Tailwind",
          "SCSS",
          "HTML",
          "CSS",
          "React 🚀",
          "Redux",
          "Next",
          "Javascript",
          "Node",
          "Express",
          "Tailwind",
          "SCSS",
          "HTML",
          "CSS",
          "React 🚀",
          "Redux",
          "Next",
          "Javascript",
          "Node",
          "Express",
          "Tailwind",
          "SCSS",
          "HTML",
          "CSS",
          "React 🚀",
          "Redux",
          "Next",
          "Javascript",
          "Node",
          "Express",
          "Tailwind",
          "SCSS",
          "HTML",
          "CSS",
          "React 🚀",
          "Redux",
          "Next",
          "Javascript",
          "Node",
          "Express",
          "Tailwind",
          "SCSS",
          "HTML",
          "CSS",
          "React 🚀",
          "Redux",
          "Next",
          "Javascript",
          "Node",
          "Express",
          "Tailwind",
          "SCSS",
          "HTML",
          "CSS",
        ]}
      />
      <TapeWidget
        rotate={"-rotate-6 -translate-y-full"}
        content={[
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
          "Express",
          "CSS",
          "React 🚀",
          "Node",
          "SCSS",
          "Redux",
          "HTML",
          "Javascript",
          "Next",
          "Tailwind",
        ]}
      />
    </div>
  );
};

export default HeroSection;
